/**
 * @file User model definition.
 *
 * Represents platform users, who may participate in deliveries
 * as customers and/or drivers. Includes account security,
 * communication details, and reputation metrics.
 */

const { DataTypes } = require('sequelize');
const sequelize = require('../config/db');

/**
 * User Schema
 *
 * @property {number} user_id - Primary key
 * @property {string} first_name - Given name of the user
 * @property {string} last_name - Family name of the user
 * @property {string} email - Unique account login and contact identifier
 * @property {string} password_hash - Secure hashed password
 * @property {string} phone - Contact phone number
 * @property {'customer'|'driver'} role - Platform role designation
 * @property {boolean} isVerified - Email verification status
 * @property {number} ratingAverage - Rolling driver reputation score
 * @property {number} totalDeliveries - Completed delivery count
 *
 * Notes:
 * - createdAt/updatedAt timestamps are auto-generated by Sequelize
 */
const User = sequelize.define('User', {
  user_id: {
    type: DataTypes.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  },
  first_name: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  last_name: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  email: {
    type: DataTypes.STRING,
    allowNull: false,
    unique: true, // Prevent duplicate accounts
    validate: {
      isEmail: true,
    },
  },
  password_hash: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  phone: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  role: {
    type: DataTypes.ENUM('customer', 'driver'),
    defaultValue: 'customer',
    allowNull: false,
  },
  isVerified: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
  },
  ratingAverage: {
    type: DataTypes.FLOAT,
    defaultValue: 0,
  },
  totalDeliveries: {
    type: DataTypes.INTEGER,
    defaultValue: 0,
  },
});

module.exports = User;
